version: '3'
services:

  mysql:
    image: mysql
    expose:
      - "3306"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    restart: always
    env_file:
      - portal.env

  portal-app:
    build: portal-app
    image: portal-app
    expose:
      - "8000"
    restart: always
    env_file:
      - portal.env
    depends_on:
      - mysql

  proxy:
    build: proxy
    image: proxy
    expose:
      - "443"
    ports:
      - "0.0.0.0:443:443"
    restart: always
    depends_on:
      - portal-app