version: '3'
services:

  portal-app:
    build: portal-app
    image: portal-app
    expose:
      - "8000"
    restart: always
    environment:
      EMAIL_PASS: ""

  # TODO: create database container
  proxy:
    build: proxy
    image: proxy
    expose:
      - "443"
    ports:
      - "0.0.0.0:443:443"
    restart: always
    depends_on:
      - portal-app