DROP TABLE IF EXISTS EMAIL_CODE;

CREATE TABLE EMAIL_CODE(
    code TEXT UNIQUE NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires TIMESTAMP
);

CREATE TRIGGER date_insert
BEFORE INSERT ON EMAIL_CODE FOR EACH ROW
BEGIN
    UPDATE NEW SET expires = DATE_ADD(CURRENT_TIMESTAMP(), INTERVAL 1 DAY);